/**
* This code was generated by v0 by Vercel.
* @see https://v0.dev/t/fwkmraT5lMg
* Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
*/

/** Add fonts into your Next.js project:

import { Arimo } from 'next/font/google'

arimo({
  subsets: ['latin'],
  display: 'swap',
})

To read more about using these font, please visit the Next.js documentation:
- App Directory: https://nextjs.org/docs/app/building-your-application/optimizing/fonts
- Pages Directory: https://nextjs.org/docs/pages/building-your-application/optimizing/fonts
**/
import { Carousel, CarouselContent, CarouselItem } from "@/components/ui/carousel"
import { Button } from "@/components/ui/button"
import { Dialog, DialogTrigger, DialogContent, DialogHeader, DialogTitle, DialogDescription, DialogBody, DialogFooter, DialogClose } from "@/components/ui/dialog"
import { Label } from "@/components/ui/label"
import { Popover, PopoverTrigger, PopoverContent } from "@/components/ui/popover"
import { Calendar } from "@/components/ui/calendar"
import { Select, SelectTrigger, SelectValue, SelectContent, SelectItem } from "@/components/ui/select"
import { RadioGroup, RadioGroupItem } from "@/components/ui/radio-group"
import { Separator } from "@/components/ui/separator"

export function Component() {
  return (
    <div className="w-full max-w-6xl mx-auto py-12 md:py-16 lg:py-20">
      <div className="relative">
        <Carousel autoPlay interval={5000} className="rounded-lg overflow-hidden">
          <CarouselContent>
            <CarouselItem>
              <img src="/placeholder.svg" alt="Activity Image" className="w-full h-[400px] md:h-[500px] object-cover" />
            </CarouselItem>
            <CarouselItem>
              <img src="/placeholder.svg" alt="Activity Image" className="w-full h-[400px] md:h-[500px] object-cover" />
            </CarouselItem>
            <CarouselItem>
              <img src="/placeholder.svg" alt="Activity Image" className="w-full h-[400px] md:h-[500px] object-cover" />
            </CarouselItem>
          </CarouselContent>
        </Carousel>
        <Button variant="outline" size="sm" className="absolute top-4 right-4 bg-background/50 hover:bg-background">
          <ExpandIcon className="h-5 w-5" />
          <span className="sr-only">Expand</span>
        </Button>
      </div>
      <div className="grid md:grid-cols-2 gap-8 mt-8 md:mt-12">
        <div>
          <h1 className="text-3xl font-bold">Sunset Kayaking Tour</h1>
          <p className="text-muted-foreground mt-2">
            Experience the beauty of the coastline as the sun dips below the horizon. Join our guided kayaking tour and
            witness the stunning natural scenery.
          </p>
          <div className="flex items-center gap-4 mt-4">
            <div className="flex items-center gap-1">
              <ClockIcon className="h-5 w-5 text-primary" />
              <span>2 hours</span>
            </div>
            <div className="flex items-center gap-1">
              <MapPinIcon className="h-5 w-5 text-primary" />
              <span>Coastal Cove</span>
            </div>
          </div>
        </div>
        <div className="bg-muted rounded-lg p-6 md:p-8">
          <div className="flex items-center justify-between">
            <div>
              <span className="text-2xl font-bold">$59</span>
              <span className="text-muted-foreground text-sm">/person</span>
            </div>
            <Dialog>
              <DialogTrigger asChild>
                <Button size="lg" className="w-full">
                  Reserve Now
                </Button>
              </DialogTrigger>
              <DialogContent className="sm:max-w-[500px]">
                <DialogHeader>
                  <DialogTitle>Reserve Sunset Kayaking Tour</DialogTitle>
                  <DialogDescription>Complete the form below to reserve your spot.</DialogDescription>
                </DialogHeader>
                <div>
                  <form className="grid gap-4">
                    <div className="grid gap-2">
                      <Label htmlFor="date">Date</Label>
                      <Popover>
                        <PopoverTrigger asChild>
                          <Button variant="outline" className="flex-col items-start w-full h-auto">
                            <span className="font-semibold uppercase text-[0.65rem]">Select Date</span>
                            <span className="font-normal">{new Date().toLocaleDateString()}</span>
                          </Button>
                        </PopoverTrigger>
                        <PopoverContent className="p-0 max-w-[276px]">
                          <Calendar />
                        </PopoverContent>
                      </Popover>
                    </div>
                    <div className="grid gap-2">
                      <Label htmlFor="guests">Guests</Label>
                      <Select>
                        <SelectTrigger className="h-auto">
                          <SelectValue
                            placeholder={
                              <div className="flex flex-col items-start">
                                <span className="font-semibold uppercase text-[0.65rem]">Guests</span>
                                <span className="font-normal">2 adults</span>
                              </div>
                            }
                          />
                        </SelectTrigger>
                        <SelectContent>
                          <SelectItem value="1">1 adult</SelectItem>
                          <SelectItem value="2">2 adults</SelectItem>
                          <SelectItem value="3">2 adults + 1 child</SelectItem>
                          <SelectItem value="other">Other</SelectItem>
                        </SelectContent>
                      </Select>
                    </div>
                    <div className="grid gap-2">
                      <Label htmlFor="payment">Payment Method</Label>
                      <RadioGroup defaultValue="card">
                        <div className="flex items-center gap-4">
                          <Label htmlFor="card" className="flex items-center gap-2 cursor-pointer">
                            <RadioGroupItem id="card" value="card" />
                            <CreditCardIcon className="h-6 w-6" />
                            Credit Card
                          </Label>
                          <Label htmlFor="paypal" className="flex items-center gap-2 cursor-pointer">
                            <RadioGroupItem id="paypal" value="paypal" />
                            <WalletCardsIcon className="h-6 w-6" />
                            PayPal
                          </Label>
                        </div>
                      </RadioGroup>
                    </div>
                  </form>
                </div>
                <DialogFooter>
                  <div className="grid gap-2">
                    <div className="flex items-center justify-between">
                      <div className="text-muted-foreground">$59 x 2 people</div>
                      <div>$118</div>
                    </div>
                    <Separator />
                    <div className="flex items-center justify-between font-medium">
                      <div>Total</div>
                      <div>$118</div>
                    </div>
                  </div>
                  <div className="mt-4 flex justify-end gap-2">
                    <div>
                      <Button variant="outline">Cancel</Button>
                    </div>
                    <Button>Reserve</Button>
                  </div>
                </DialogFooter>
              </DialogContent>
            </Dialog>
          </div>
        </div>
      </div>
    </div>
  )
}

function ClockIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <circle cx="12" cy="12" r="10" />
      <polyline points="12 6 12 12 16 14" />
    </svg>
  )
}


function CreditCardIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <rect width="20" height="14" x="2" y="5" rx="2" />
      <line x1="2" x2="22" y1="10" y2="10" />
    </svg>
  )
}


function ExpandIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="m21 21-6-6m6 6v-4.8m0 4.8h-4.8" />
      <path d="M3 16.2V21m0 0h4.8M3 21l6-6" />
      <path d="M21 7.8V3m0 0h-4.8M21 3l-6 6" />
      <path d="M3 7.8V3m0 0h4.8M3 3l6 6" />
    </svg>
  )
}


function MapPinIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M20 10c0 6-8 12-8 12s-8-6-8-12a8 8 0 0 1 16 0Z" />
      <circle cx="12" cy="10" r="3" />
    </svg>
  )
}


function WalletCardsIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <rect width="18" height="18" x="3" y="3" rx="2" />
      <path d="M3 9a2 2 0 0 1 2-2h14a2 2 0 0 1 2 2" />
      <path d="M3 11h3c.8 0 1.6.3 2.1.9l1.1.9c1.6 1.6 4.1 1.6 5.7 0l1.1-.9c.5-.5 1.3-.9 2.1-.9H21" />
    </svg>
  )
}


function XIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M18 6 6 18" />
      <path d="m6 6 12 12" />
    </svg>
  )
}
