// import type { Metadata } from "next"

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// }

import { Poppins } from "next/font/google"
import { Cabin } from "next/font/google"
import "../globals.css"
import "../styles.css"

import React from "react"

const poppins = Poppins({
  weight: "300",
  subsets: ["latin"],
  display: "swap",
  variable: "--font-poppins",
})
const cabin = Cabin({
  subsets: ["latin"],
  display: "swap",
  variable: "--font-cabin",
})

export async function generateStaticParams() {
  return [
    { locale: "en" },
    { locale: "nl" },
    { locale: "es" },
    { locale: "ru" },
  ]
}

export default function Layout({
  children,
  params,
}: Readonly<{
  children: React.ReactNode
  params?: any
}>) {
  console.log({ params })
  return (
    <html lang={params.locale}>
      <body className={poppins.variable + " " + cabin.variable}>
        <div className="flex flex-col min-h-[100dvh]">{children}</div>
      </body>
    </html>
  )
}
