// Multilingual patterns for context extraction in chat interface

export const patterns = {
  guests: {
    en: /\b(\d+)\s+(guests?|people)\b/,
    nl: /\b(\d+)\s+(gasten|mensen|personen)\b/,
    es: /\b(\d+)\s+(huéspedes|personas)\b/,
    de: /\b(\d+)\s+(gäste|personen)\b/,
    ru: /\b(\d+)\s+(guests?|people)\b/,
  },
  nights: {
    en: /\b(\d+)\s+(nights?)\b/,
    nl: /\b(\d+)\s+(nachten)\b/,
    es: /\b(\d+)\s+(noches)\b/,
    de: /\b(\d+)\s+(nächte)\b/,
    ru: /\b(\d+)\s+(noches)\b/,
  },
  months: {
    en: /\b(january|february|march|april|may|june|july|august|september|october|november|december)\s+\d{1,2}\b/gi,
    nl: /\b(januari|februari|maart|april|mei|juni|juli|augustus|september|oktober|november|december)\s+\d{1,2}\b/gi,
    es: /\b(enero|febrero|marzo|abril|mayo|junio|julio|agosto|septiembre|octubre|noviembre|diciembre)\s+\d{1,2}\b/gi,
    de: /\b(januar|februar|märz|april|mai|juni|juli|august|september|oktober|november|dezember)\s+\d{1,2}\b/gi,
    ru: /\b(enero|febrero|marzo|abril|mayo|junio|julio|agosto|septiembre|octubre|noviembre|diciembre)\s+\d{1,2}\b/gi,
  },
  amenities: {
    en: [
      "ac",
      "air conditioning",
      "wifi",
      "pool",
      "kitchen",
      "parking",
      "beach",
      "ocean",
    ],
    nl: [
      "ac",
      "airconditioning",
      "wifi",
      "zwembad",
      "keuken",
      "parkeerplaats",
      "strand",
      "zee",
    ],
    es: [
      "ac",
      "aire acondicionado",
      "wifi",
      "piscina",
      "cocina",
      "estacionamiento",
      "playa",
      "océano",
    ],
    de: [
      "ac",
      "klimaanlage",
      "wifi",
      "pool",
      "küche",
      "parkplatz",
      "strand",
      "meer",
    ],
    ru: [
      "ac",
      "aire acondicionado",
      "wifi",
      "piscina",
      "cocina",
      "estacionamiento",
      "playa",
      "océano",
    ],
  },
  interests: {
    en: [
      "price",
      "cost",
      "availability",
      "booking",
      "reservation",
      "cancel",
      "payment",
    ],
    nl: [
      "prijs",
      "kosten",
      "beschikbaarheid",
      "boeking",
      "reservering",
      "annuleren",
      "betaling",
    ],
    es: [
      "precio",
      "costo",
      "disponibilidad",
      "reserva",
      "reservación",
      "cancelar",
      "pago",
    ],
    de: [
      "preis",
      "kosten",
      "verfügbarkeit",
      "buchung",
      "reservierung",
      "stornieren",
      "zahlung",
    ],
    ru: [
      "precio",
      "costo",
      "disponibilidad",
      "reserva",
      "reservación",
      "cancelar",
      "pago",
    ],
  },
} as const
