// Enhanced intent detection with synonyms and typo tolerance
export type UserIntent =
  | "amenities"
  | "pricing"
  | "payment"
  | "cancellation"
  | "logistics"
  | "tours"
  | "reviews"
  | "availability"
  | "general"

// Enhanced keyword mappings with multilingual support
const intentKeywords: Record<UserIntent, string[]> = {
  amenities: [
    // English
    "amenit",
    "facilit",
    "feature",
    "pool",
    "wifi",
    "kitchen",
    "equipment",
    "convenience",
    "facilities",
    "features",
    "equipment",
    "conveniences",
    "services",
    "utilities",
    "air conditioning",
    "ac",
    "heating",
    "parking",
    "gym",
    "fitness",
    "laundry",
    "beach",
    "ocean",
    "view",
    "balcony",
    "terrace",
    "garden",
    "bbq",
    "grill",
    // Spanish
    "amenidades",
    "instalaciones",
    "características",
    "piscina",
    "wifi",
    "cocina",
    "equipamiento",
    "comodidades",
    "servicios",
    "utilidades",
    "aire acondicionado",
    "calefacción",
    "estacionamiento",
    "gimnasio",
    "fitness",
    "lavandería",
    "playa",
    "océano",
    "vista",
    "balcón",
    "terraza",
    "jardín",
    "parrilla",
    "asador",
    "cosas",
    "qué hay",
    "qué tiene",
    "dispone de",
    "incluye",
    // Dutch
    "faciliteiten",
    "kenmerken",
    "zwembad",
    "wifi",
    "keuken",
    "apparatuur",
    "gemakken",
    "diensten",
    "nutsvoorzieningen",
    "airconditioning",
    "verwarming",
    "parkeerplaats",
    "sportschool",
    "fitness",
    "wasserette",
    "strand",
    "oceaan",
    "zicht",
    "balkon",
    "terras",
    "tuin",
    "bbq",
    "grill",
    "wat is er",
    "wat heb je",
    "beschikt over",
    // German
    "ausstattung",
    "einrichtungen",
    "merkmale",
    "pool",
    "wifi",
    "küche",
    "ausrüstung",
    "annehmlichkeiten",
    "dienstleistungen",
    "versorgungsleistungen",
    "klimaanlage",
    "heizung",
    "parkplatz",
    "fitnessstudio",
    "fitness",
    "wäscheservice",
    "strand",
    "meer",
    "blick",
    "balkon",
    "terrasse",
    "garten",
    "grill",
    "was gibt es",
    "was haben sie",
    "verfügt über",
    // Russian
    "удобства",
    "сооружения",
    "особенности",
    "бассейн",
    "вайфай",
    "кухня",
    "оборудование",
    "комфорт",
    "услуги",
    "коммунальные услуги",
    "кондиционер",
    "отопление",
    "парковка",
    "спортзал",
    "фитнес",
    "прачечная",
    "пляж",
    "океан",
    "вид",
    "балкон",
    "терраса",
    "сад",
    "барбекю",
    "гриль",
    "что есть",
    "что имеется",
    // Common typos across languages
    "amenites",
    "facilities",
    "featurs",
    "conviniences",
    "amneties",
  ],
  pricing: [
    // English
    "price",
    "cost",
    "fee",
    "discount",
    "season",
    "rate",
    "pricing",
    "rates",
    "charge",
    "payment",
    "expense",
    "tariff",
    "value",
    "amount",
    "money",
    "cheap",
    "expensive",
    "affordable",
    "budget",
    "deal",
    "offer",
    "promotion",
    // Spanish
    "precio",
    "costo",
    "tarifa",
    "descuento",
    "temporada",
    "tasa",
    "precios",
    "tasas",
    "cargo",
    "pago",
    "gasto",
    "valor",
    "cantidad",
    "dinero",
    "barato",
    "caro",
    "asequible",
    "presupuesto",
    "oferta",
    "promoción",
    // Dutch
    "prijs",
    "kosten",
    "tarief",
    "korting",
    "seizoen",
    "tarief",
    "prijzen",
    "tarieven",
    "kosten",
    "betaling",
    "uitgave",
    "waarde",
    "bedrag",
    "geld",
    "goedkoop",
    "duur",
    "betaalbaar",
    "budget",
    "aanbieding",
    "promotie",
    // German
    "preis",
    "kosten",
    "gebühr",
    "rabatt",
    "saison",
    "satz",
    "preise",
    "sätze",
    "belastung",
    "zahlung",
    "ausgabe",
    "wert",
    "betrag",
    "geld",
    "billig",
    "teuer",
    "erschwinglich",
    "budget",
    "angebot",
    "promotion",
    // Russian
    "цена",
    "стоимость",
    "плата",
    "скидка",
    "сезон",
    "ставка",
    "цены",
    "ставки",
    "расходы",
    "оплата",
    "затраты",
    "тариф",
    "сумма",
    "деньги",
    "дешевый",
    "дорогой",
    "доступный",
    "бюджет",
    "предложение",
    "акция",
    "промоушн",
    // Common typos across languages
    "prce",
    "cst",
    "dicsount",
    "seasson",
    "rates",
  ],
  payment: [
    // English
    "payment",
    "pay",
    "card",
    "stripe",
    "paypal",
    "transaction",
    "billing",
    "charge",
    "purchase",
    "checkout",
    "credit",
    "debit",
    "transfer",
    "secure",
    "safe",
    "method",
    "option",
    "processor",
    "gateway",
    // Spanish
    "pago",
    "pagar",
    "tarjeta",
    "transacción",
    "facturación",
    "cargo",
    "compra",
    "caja",
    "crédito",
    "débito",
    "transferencia",
    "seguro",
    "método",
    "opción",
    "procesador",
    "puerta de enlace",
    // Dutch
    "betaling",
    "betalen",
    "kaart",
    "transactie",
    "facturering",
    "kosten",
    "aankoop",
    "afrekenen",
    "credit",
    "debet",
    "overdracht",
    "veilig",
    "methode",
    "optie",
    "processor",
    "gateway",
    // German
    "zahlung",
    "bezahlen",
    "karte",
    "transaktion",
    "abrechnung",
    "gebühr",
    "kauf",
    "kasse",
    "kredit",
    "debet",
    "überweisung",
    "sicher",
    "methode",
    "option",
    "prozessor",
    "gateway",
    // Russian
    "платеж",
    "платить",
    "карта",
    "транзакция",
    "выставление счета",
    "плата",
    "покупка",
    "касса",
    "кредит",
    "дебет",
    "перевод",
    "безопасный",
    "метод",
    "опция",
    "процессор",
    "шлюз",
    // Common typos across languages
    "paymnet",
    "paymet",
    "crdit",
    "trasnfer",
  ],
  cancellation: [
    // English
    "cancel",
    "refund",
    "modification",
    "change",
    "cancellation",
    "modify",
    "alter",
    "adjust",
    "revoke",
    "terminate",
    "reschedule",
    "postpone",
    "policy",
    "rules",
    "terms",
    "conditions",
    "penalty",
    "fee",
    "refundable",
    // Spanish
    "cancelar",
    "reembolso",
    "modificación",
    "cambio",
    "cancelación",
    "modificar",
    "alterar",
    "ajustar",
    "revocar",
    "terminar",
    "reprogramar",
    "posponer",
    "política",
    "reglas",
    "términos",
    "condiciones",
    "penalización",
    "cuota",
    "reembolsable",
    // Dutch
    "annuleren",
    "terugbetaling",
    "wijziging",
    "verandering",
    "annulering",
    "aanpassen",
    "wijzigen",
    "intrekken",
    "beëindigen",
    "verplaatsen",
    "uitstellen",
    "beleid",
    "regels",
    "voorwaarden",
    "condities",
    "straf",
    "kosten",
    "terugbetaalbaar",
    // German
    "stornieren",
    "erstattung",
    "änderung",
    "veränderung",
    "stornierung",
    "ändern",
    "anpassen",
    "widerrufen",
    "beenden",
    "verschieben",
    "verschieben",
    "richtlinie",
    "regeln",
    "bedingungen",
    "konditionen",
    "strafe",
    "gebühr",
    "erstattbar",
    // Russian
    "отмена",
    "возврат",
    "модификация",
    "изменение",
    "аннуляция",
    "модифицировать",
    "изменять",
    "корректировать",
    "отозвать",
    "прекратить",
    "перенести",
    "отложить",
    "политика",
    "правила",
    "условия",
    "штраф",
    "плата",
    "возвращаемый",
    // Common typos across languages
    "cancle",
    "refud",
    "modifcation",
    "cancelllation",
  ],
  logistics: [
    // English
    "check",
    "arrival",
    "departure",
    "transport",
    "direction",
    "parking",
    "checkin",
    "checkout",
    "transportation",
    "travel",
    "location",
    "address",
    "route",
    "access",
    "entry",
    "exit",
    "pickup",
    "dropoff",
    "shuttle",
    "transfer",
    "airport",
    "car",
    "rental",
    "taxi",
    "uber",
    "bus",
    "directions",
    "map",
    // Spanish
    "chequear",
    "llegada",
    "salida",
    "transporte",
    "dirección",
    "estacionamiento",
    "check-in",
    "check-out",
    "transportación",
    "viaje",
    "ubicación",
    "dirección",
    "ruta",
    "acceso",
    "entrada",
    "salida",
    "recoger",
    "dejar",
    "shuttle",
    "transferencia",
    "aeropuerto",
    "coche",
    "alquiler",
    "taxi",
    "uber",
    "autobús",
    "direcciones",
    "mapa",
    // Dutch
    "controleren",
    "aankomst",
    "vertrek",
    "transport",
    "richting",
    "parkeerplaats",
    "inchecken",
    "uitchecken",
    "vervoer",
    "reis",
    "locatie",
    "adres",
    "route",
    "toegang",
    "ingang",
    "uitgang",
    "ophalen",
    "afzetten",
    "shuttle",
    "overdracht",
    "luchthaven",
    "auto",
    "huur",
    "taxi",
    "uber",
    "bus",
    "routebeschrijving",
    "kaart",
    // German
    "überprüfen",
    "ankunft",
    "abreise",
    "transport",
    "richtung",
    "parkplatz",
    "einchecken",
    "auschecken",
    "transportation",
    "reise",
    "standort",
    "adresse",
    "route",
    "zugang",
    "eintritt",
    "austritt",
    "abholen",
    "absetzen",
    "shuttle",
    "transfer",
    "flughafen",
    "auto",
    "miete",
    "taxi",
    "uber",
    "bus",
    "wegbeschreibung",
    "karte",
    // Russian
    "проверить",
    "прибытие",
    "выезд",
    "транспорт",
    "направление",
    "парковка",
    "регистрация",
    "выписка",
    "транспортировка",
    "путешествие",
    "местоположение",
    "адрес",
    "маршрут",
    "доступ",
    "вход",
    "выход",
    "забрать",
    "оставить",
    "шаттл",
    "пересадка",
    "аэропорт",
    "машина",
    "аренда",
    "такси",
    "убер",
    "автобус",
    "направления",
    "карта",
    // Common typos across languages
    "chek",
    "arival",
    "departre",
    "trasnport",
    "directon",
    "parkng",
  ],
  tours: [
    // English
    "tour",
    "activity",
    "excursion",
    "trip",
    "experience",
    "adventure",
    "journey",
    "travel",
    "expedition",
    "outing",
    "sightseeing",
    "attraction",
    "destination",
    "event",
    "guide",
    "local",
    "book",
    "reserve",
    "schedule",
    "available",
    "price",
    "duration",
    "time",
    // Spanish
    "tour",
    "actividad",
    "excursión",
    "viaje",
    "experiencia",
    "aventura",
    "travesía",
    "viajar",
    "expedición",
    "salida",
    "turismo",
    "atracción",
    "destino",
    "evento",
    "guía",
    "local",
    "reservar",
    "reserva",
    "horario",
    "disponible",
    "precio",
    "duración",
    "tiempo",
    // Dutch
    "tour",
    "activiteit",
    "excursie",
    "reis",
    "ervaring",
    "avontuur",
    "tocht",
    "reizen",
    "expeditie",
    "uitje",
    "bezienswaardigheden",
    "attractie",
    "bestemming",
    "evenement",
    "gids",
    "lokaal",
    "boeken",
    "reserveren",
    "schema",
    "beschikbaar",
    "prijs",
    "duur",
    "tijd",
    // German
    "tour",
    "aktivität",
    "ausflug",
    "reise",
    "erfahrung",
    "abenteuer",
    "fahrt",
    "reisen",
    "expedition",
    "ausflug",
    "besichtigung",
    "attraktion",
    "ziel",
    "veranstaltung",
    "führer",
    "lokal",
    "buchen",
    "reservieren",
    "zeitplan",
    "verfügbar",
    "preis",
    "dauer",
    "zeit",
    // Russian
    "тур",
    "активность",
    "экскурсия",
    "поездка",
    "опыт",
    "приключение",
    "путешествие",
    "экспедиция",
    "выход",
    "осмотр достопримечательностей",
    "привлекательность",
    "назначение",
    "событие",
    "гид",
    "местный",
    "бронировать",
    "резервировать",
    "расписание",
    "доступный",
    "цена",
    "продолжительность",
    "время",
    // Common typos across languages
    "tou",
    "activty",
    "excursin",
    "trip",
    "experince",
  ],
  reviews: [
    // English
    "review",
    "rating",
    "guest",
    "experience",
    "feedback",
    "testimonial",
    "opinion",
    "comment",
    "evaluation",
    "assessment",
    "recommendation",
    "score",
    "stars",
    "average",
    "quality",
    "satisfaction",
    "service",
    "cleanliness",
    // Spanish
    "reseña",
    "calificación",
    "huésped",
    "experiencia",
    "comentarios",
    "testimonio",
    "opinión",
    "comentario",
    "evaluación",
    "valoración",
    "recomendación",
    "puntuación",
    "estrellas",
    "promedio",
    "calidad",
    "satisfacción",
    "servicio",
    "limpieza",
    // Dutch
    "review",
    "beoordeling",
    "gast",
    "ervaring",
    "feedback",
    "getuigenis",
    "mening",
    "opmerking",
    "evaluatie",
    "beoordeling",
    "aanbeveling",
    "score",
    "sterren",
    "gemiddelde",
    "kwaliteit",
    "tevredenheid",
    "service",
    "netheid",
    // German
    "bewertung",
    "bewertung",
    "gast",
    "erfahrung",
    "feedback",
    "testimonial",
    "meinung",
    "kommentar",
    "bewertung",
    "einschätzung",
    "empfehlung",
    "punktzahl",
    "sterne",
    "durchschnitt",
    "qualität",
    "zufriedenheit",
    "service",
    "sauberkeit",
    // Russian
    "отзыв",
    "рейтинг",
    "гость",
    "опыт",
    "обратная связь",
    "отзыв",
    "мнение",
    "комментарий",
    "оценка",
    "оценка",
    "рекомендация",
    "счет",
    "звезды",
    "средний",
    "качество",
    "удовлетворенность",
    "сервис",
    "чистота",
    // Common typos across languages
    "reviw",
    "rating",
    "gest",
    "experince",
    "feddback",
  ],
  availability: [
    // English
    "availability",
    "available",
    "book",
    "booking",
    "reservation",
    "schedule",
    "open",
    "free",
    "vacant",
    "unoccupied",
    "reserve",
    "dates",
    "calendar",
    "check",
    "confirm",
    "status",
    "when",
    "time",
    "period",
    // Spanish
    "disponibilidad",
    "disponible",
    "reservar",
    "reserva",
    "reservación",
    "horario",
    "abierto",
    "libre",
    "vacante",
    "desocupado",
    "reservar",
    "fechas",
    "calendario",
    "verificar",
    "confirmar",
    "estado",
    "cuándo",
    "tiempo",
    "período",
    // Dutch
    "beschikbaarheid",
    "beschikbaar",
    "boeken",
    "boeking",
    "reservering",
    "schema",
    "open",
    "vrij",
    "vacant",
    "onbezet",
    "reserveren",
    "data",
    "kalender",
    "controleren",
    "bevestigen",
    "status",
    "wanneer",
    "tijd",
    "periode",
    // German
    "verfügbarkeit",
    "verfügbar",
    "buchen",
    "buchung",
    "reservierung",
    "zeitplan",
    "offen",
    "frei",
    "vacant",
    "unbesetzt",
    "reservieren",
    "daten",
    "kalender",
    "überprüfen",
    "bestätigen",
    "status",
    "wann",
    "zeit",
    "periode",
    // Russian
    "доступность",
    "доступный",
    "бронировать",
    "бронирование",
    "резервирование",
    "расписание",
    "открытый",
    "свободный",
    "вакантный",
    "незанятый",
    "резервировать",
    "даты",
    "календарь",
    "проверить",
    "подтвердить",
    "статус",
    "когда",
    "время",
    "период",
    // Common typos across languages
    "availablity",
    "availble",
    "booking",
    "reservtion",
    "schedul",
  ],
  general: [
    // English
    "information",
    "info",
    "details",
    "about",
    "help",
    "question",
    "contact",
    "support",
    "assistance",
    "guidance",
    "advice",
    "recommendation",
    // Spanish
    "información",
    "información",
    "detalles",
    "acerca de",
    "ayuda",
    "pregunta",
    "contacto",
    "soporte",
    "asistencia",
    "orientación",
    "consejo",
    "recomendación",
    // Dutch
    "informatie",
    "info",
    "details",
    "over",
    "hulp",
    "vraag",
    "contact",
    "ondersteuning",
    "bijstand",
    "begeleiding",
    "advies",
    "aanbeveling",
    // German
    "information",
    "info",
    "details",
    "über",
    "hilfe",
    "frage",
    "kontakt",
    "unterstützung",
    "hilfe",
    "leitung",
    "rat",
    "empfehlung",
    // Russian
    "информация",
    "инфо",
    "детали",
    "о",
    "помощь",
    "вопрос",
    "контакт",
    "поддержка",
    "помощь",
    "руководство",
    "совет",
    "рекомендация",
  ],
}

// Fuzzy matching function for typo tolerance
function fuzzyMatch(term: string, keyword: string): boolean {
  // Exact match
  if (term.includes(keyword)) return true

  // Check if keyword is contained in term
  if (keyword.includes(term)) return true

  // Simple typo tolerance: check if most characters match
  if (term.length >= 3 && keyword.length >= 3) {
    const shorter = term.length < keyword.length ? term : keyword
    const longer = term.length >= keyword.length ? term : keyword

    // Check if at least 70% of characters match in order
    let matches = 0
    let longerIndex = 0

    for (let i = 0; i < shorter.length && longerIndex < longer.length; i++) {
      if (shorter[i] === longer[longerIndex]) {
        matches++
        longerIndex++
      } else {
        // Skip one character in longer string
        longerIndex++
        if (shorter[i] === longer[longerIndex]) {
          matches++
          longerIndex++
        }
      }
    }

    return matches / shorter.length >= 0.7
  }

  return false
}

export function detectUserIntent(query: string): UserIntent {
  const lowerQuery = query.toLowerCase().trim()

  // Check each intent type
  for (const [intent, keywords] of Object.entries(intentKeywords)) {
    for (const keyword of keywords) {
      if (fuzzyMatch(lowerQuery, keyword.toLowerCase())) {
        return intent as UserIntent
      }
    }
  }

  return "general"
}

// Get progress message based on intent
export function getProgressMessage(intent: UserIntent): string {
  switch (intent) {
    case "availability":
      return "Checking availability..."
    case "pricing":
      return "Calculating pricing..."
    case "amenities":
    case "general":
      return "Getting property information..."
    case "payment":
      return "Processing payment information..."
    case "cancellation":
      return "Checking cancellation policy..."
    case "logistics":
      return "Getting logistics information..."
    case "tours":
      return "Finding available tours..."
    case "reviews":
      return "Loading guest reviews..."
    default:
      return "Processing your request..."
  }
}

// Enhanced query terms for better matching
export function enhanceQuery(query: string): string[] {
  const lowerQuery = query.toLowerCase()
  const terms = [lowerQuery]
  const intent = detectUserIntent(query)

  // Add synonyms based on detected intent
  const keywords = intentKeywords[intent]
  keywords.forEach(keyword => {
    if (
      lowerQuery.includes(keyword.split(" ")[0]) &&
      !terms.includes(keyword)
    ) {
      terms.push(keyword)
    }
  })

  return terms
}
